version: 1.0
provider:
  name: openfaas
  gateway: https://openfaas.bitcoin-studio.com

functions:
  send-email:
    lang: node-custom
    handler: ./function
    image: janakasteph/send-email:${DEV:-latest}
    secrets:
      - send-email-config
      - hmac-cluster